# =============================================================================
# AQUILA PROJECT - PRE-COMMIT HOOKS
# =============================================================================
# Instalar: pre-commit install
# Ejecutar manualmente: pre-commit run --all-files
# =============================================================================

repos:
  # ---------------------------------------------------------------------------
  # General file checks
  # ---------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevenir commits a branches protegidas
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'production']

      # Verificar archivos
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

      # Limpieza de archivos
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # ---------------------------------------------------------------------------
  # Secret detection (CRÍTICO)
  # ---------------------------------------------------------------------------
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            docs/security/CREDENTIALS_TO_ROTATE\.md|
            \.env\.example|
            requirements.*\.txt
          )$

  # ---------------------------------------------------------------------------
  # Python code formatting
  # ---------------------------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
        args: ['--line-length=120']
        files: ^(aquila_app|aquila_bureaus_sdk)/.*\.py$

  # ---------------------------------------------------------------------------
  # Import sorting
  # ---------------------------------------------------------------------------
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '120']
        files: ^(aquila_app|aquila_bureaus_sdk)/.*\.py$

  # ---------------------------------------------------------------------------
  # Linting
  # ---------------------------------------------------------------------------
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--extend-ignore=E203,E501']
        files: ^(aquila_app|aquila_bureaus_sdk)/.*\.py$

  # ---------------------------------------------------------------------------
  # Security scanning
  # ---------------------------------------------------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-r', 'aquila_app/', 'aquila_bureaus_sdk/', '-f', 'screen']
        exclude: ^tests/

  # ---------------------------------------------------------------------------
  # Type checking
  # ---------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--python-version=3.12']
        additional_dependencies: ['types-PyYAML', 'types-redis']
        files: ^(aquila_app|aquila_bureaus_sdk)/.*\.py$

# =============================================================================
# CONFIGURACIÓN ADICIONAL
# =============================================================================

# Opciones globales
default_language_version:
  python: python3.12

# Stages personalizados
default_stages: [pre-commit, pre-push]

# Execution speed optimization
fail_fast: false
