blank_issues_enabled: false
contact_links:
  - name: Documentación
    url: https://github.com/elgomy/aquila_project/tree/main/docs
    about: Consulta la documentación completa del proyecto
  - name: Guía de Contribución
    url: https://github.com/elgomy/aquila_project/blob/main/CONTRIBUTING.md
    about: Lee cómo contribuir al proyecto
